export default function Home() {
  return (
    <div className="flex flex-col justify-center items-center min-h-screen">
      <p className="w-1/2">
       Lorem ipsum odor amet, consectetuer adipiscing elit. Senectus curae aliquam interdum massa bibendum dolor lacus vulputate. Mauris proin ad integer volutpat est. Maecenas nec himenaeos odio dis phasellus pretium fringilla lacus. Aliquet ridiculus gravida aliquam bibendum torquent phasellus. Tincidunt mauris convallis efficitur; efficitur mauris sociosqu. Quis penatibus facilisi finibus venenatis accumsan platea ultrices. Consectetur auctor volutpat at erat ligula risus. Mi rhoncus convallis vehicula dictum purus. Vehicula nam luctus nisl cubilia dictum habitasse tellus per porta. Commodo consequat semper condimentum praesent vel, parturient ultricies quam. Cubilia eleifend nibh lobortis nascetur parturient ridiculus justo sed. Ut magnis inceptos placerat efficitur neque praesent sodales adipiscing. Nibh duis mollis, sit proin suscipit litora dignissim metus. Consectetur augue purus sociosqu enim semper gravida rutrum efficitur nascetur. Lacus at elementum penatibus ac ex malesuada est class mollis. Senectus diam erat suscipit ex leo accumsan. Quam potenti bibendum turpis magnis vivamus viverra vivamus a. Urna elit tellus ante proin mus primis sem. Blandit rutrum sodales proin finibus risus. Praesent nostra sem non ornare hac platea. Vehicula varius eleifend consequat et vulputate odio semper. Risus quis magna pretium curabitur justo senectus auctor erat primis. Phasellus massa tortor luctus, nibh condimentum dis. Ultricies sollicitudin conubia metus cras urna elit efficitur rhoncus. Auctor purus magna iaculis rutrum metus risus.
        Lorem ipsum odor amet, consectetuer adipiscing elit. Senectus curae aliquam interdum massa bibendum dolor lacus vulputate. Mauris proin ad integer volutpat est. Maecenas nec himenaeos odio dis phasellus pretium fringilla lacus. Aliquet ridiculus gravida aliquam bibendum torquent phasellus. Tincidunt mauris convallis efficitur; efficitur mauris sociosqu. Quis penatibus facilisi finibus venenatis accumsan platea ultrices. Consectetur auctor volutpat at erat ligula risus. Mi rhoncus convallis vehicula dictum purus. Vehicula nam luctus nisl cubilia dictum habitasse tellus per porta. Commodo consequat semper condimentum praesent vel, parturient ultricies quam. Cubilia eleifend nibh lobortis nascetur parturient ridiculus justo sed. Ut magnis inceptos placerat efficitur neque praesent sodales adipiscing. Nibh duis mollis, sit proin suscipit litora dignissim metus. Consectetur augue purus sociosqu enim semper gravida rutrum efficitur nascetur. Lacus at elementum penatibus ac ex malesuada est class mollis. Senectus diam erat suscipit ex leo accumsan. Quam potenti bibendum turpis magnis vivamus viverra vivamus a. Urna elit tellus ante proin mus primis sem. Blandit rutrum sodales proin finibus risus. Praesent nostra sem non ornare hac platea. Vehicula varius eleifend consequat et vulputate odio semper. Risus quis magna pretium curabitur justo senectus auctor erat primis. Phasellus massa tortor luctus, nibh condimentum dis. Ultricies sollicitudin conubia metus cras urna elit efficitur rhoncus. Auctor purus magna iaculis rutrum metus risus.
        Lorem ipsum odor amet, consectetuer adipiscing elit. Senectus curae aliquam interdum massa bibendum dolor lacus vulputate. Mauris proin ad integer volutpat est. Maecenas nec himenaeos odio dis phasellus pretium fringilla lacus. Aliquet ridiculus gravida aliquam bibendum torquent phasellus. Tincidunt mauris convallis efficitur; efficitur mauris sociosqu. Quis penatibus facilisi finibus venenatis accumsan platea ultrices.

Consectetur auctor volutpat at erat ligula risus. Mi rhoncus convallis vehicula dictum purus. Vehicula nam luctus nisl cubilia dictum habitasse tellus per porta. Commodo consequat semper condimentum praesent vel, parturient ultricies quam. Cubilia eleifend nibh lobortis nascetur parturient ridiculus justo sed. Ut magnis inceptos placerat efficitur neque praesent sodales adipiscing. Nibh duis mollis, sit proin suscipit litora dignissim metus. Consectetur augue purus sociosqu enim semper gravida rutrum efficitur nascetur. Lacus at elementum penatibus ac ex malesuada est class mollis.

Senectus diam erat suscipit ex leo accumsan. Quam potenti bibendum turpis magnis vivamus viverra vivamus a. Urna elit tellus ante proin mus primis sem. Blandit rutrum sodales proin finibus risus. Praesent nostra sem non ornare hac platea. Vehicula varius eleifend consequat et vulputate odio semper. Risus quis magna pretium curabitur justo senectus auctor erat primis. Phasellus massa tortor luctus, nibh condimentum dis. Ultricies sollicitudin conubia metus cras urna elit efficitur rhoncus. Auctor purus magna iaculis rutrum metus risus.
      </p>
    </div>
  )
}

